---
- name: create object and firewall policy in Panorma
  hosts: firewall
  connection: local
  gather_facts: no
  roles:
  - role : PaloAltoNetworks.paloaltonetworks
  vars:
   provider:
      ip_address: '{{ inventory_hostname }}'
      username: admin
      password: '{{admin_password }}'
    
  tasks:
  #include ansible-vault password for hosts
  - name: include vault password variables
    include_vars: vars1.yml
  - name: set admin password
    panos_administrator:
      provider: '{{ provider }}'
      admin_username: 'admin'
      admin_password: '{{ provider.password }}'
      superuser: True
      commit: False
- name: Add the necessary service object to Panorama first
  panos_object:
    provider: '{{ provider }}'
    name: 'service-tcp-221'
    protocol: 'tcp'
    destination_port: '221'
    description: 'SSH on port 221'
    commit: false
    device_group: 'DeviceGroupA'
	
- name: Add test pre-rule to Panorama
  panos_security_rule:
    provider: '{{ provider }}'
    rule_name: 'Ansible test 1'
    description: 'An Ansible test pre-rule'
    source_zone: ['internal']
    destination_zone: ['external']
    source_ip: ['1.2.3.4']
    source_user: ['any']
    destination_ip: ['any']
    category: ['any']
    application: ['any']
    service: ['service-http']
    hip_profiles: ['any']
    action: 'allow'
    device_group: 'DeviceGroupA'
    commit: False	
- name: Create dynamic NAT rule on Panorama
  panos_nat_rule:
    provider: '{{ provider }}'
    rule_name: 'Web SSH inbound'
    source_zone: ['external']
    destination_zone: 'external'
    source_ip: ['any']
    destination_ip: ['10.0.0.100']
    service: 'service-tcp-221'
    snat_type: 'dynamic-ip-and-port'
    snat_interface: ['ethernet1/2']
    dnat_address: '10.0.1.101'
    dnat_port: '22'
    device_group: 'DeviceGroupA'
    commit: False
    #check if ready
 - name: check if ready
   panos_check:
        provider: '{{provider}}'
        timeout: 0       
 - name: commit candidate configs on panorama
   panos_commit_panorama:
       provider: '{{ provider }}'
- name: commit specific device group changes on panorama
  panos_commit_panorama:
      provider: '{{ provider }}'
      device_groups: ['DeviceGroupA']
       
        
        #ansible-playbook --ask-vault-pass 
        #ansible-vault edit vars
